on:
  pull_request:
    branches:
      - main

name: minimal-test
jobs:
  minimal-test:
    name: Build and test ZOT - minimal edition
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    services:
      s3mock:
        image: ghcr.io/project-zot/localstack/localstack:0.13.2
        env:
          SERVICES: s3
        ports:
          - 4563-4599:4563-4599
          - 9090:8080
    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          go install github.com/swaggo/swag/cmd/swag@latest
          go mod download
          sudo apt-get update
          sudo apt-get install rpm
          sudo apt-get install snapd
          sudo apt-get install libgpgme-dev libassuan-dev libbtrfs-dev libdevmapper-dev pkg-config
          git clone https://github.com/containers/skopeo -b v1.6.1 $GITHUB_WORKSPACE/src/github.com/containers/skopeo
          cd $GITHUB_WORKSPACE/src/github.com/containers/skopeo && make bin/skopeo
          cd $GITHUB_WORKSPACE
          curl -Lo notation.tar.gz https://github.com/notaryproject/notation/releases/download/v0.7.1-alpha.1/notation_0.7.1-alpha.1_linux_amd64.tar.gz
          sudo tar xvzf notation.tar.gz -C /usr/bin notation
          go install github.com/wadey/gocovmerge@latest
      - name: Run build and test minimally
        timeout-minutes: 60
        run: |
          echo "Building for $OS:$ARCH"
          cd $GITHUB_WORKSPACE
          if [[ $OS == "linux" && $ARCH == "amd64" ]]; then
            make OS=$OS ARCH=$ARCH minimal
            sudo env "PATH=$PATH" make privileged-test
          fi
        env:
          S3MOCK_ENDPOINT: localhost:4566
          AWS_ACCESS_KEY_ID: fake
          AWS_SECRET_ACCESS_KEY: fake
          OS: ${{ matrix.os }}
          ARCH: ${{ matrix.arch }}
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
