on:
  release:
    types:
      - published

name: release-on-zui

jobs:
  push-zui:
    name: Release on zui
    runs-on: ubuntu-latest
    steps:
      - run: |
          touch placeholder.txt
          echo "size more than 0" > placeholder.txt
      - name: Release on zui
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.ZUI_TOKEN }}
          file: placeholder.txt
          repo_name: project-zot/zui
          tag: ${{ github.event.release.tag_name }}
          release_name: ${{ github.event.release.name }}
          body: ${{ github.event.release.body }}
